services:
  api-gemma2:
    container_name: api-gemma2
    build: api-gemma2
    volumes:
      - ./api-gemma2/src:/app/src
    networks:
      - custom_network
  app:
    container_name: app
    build: app-next
    volumes:
      - ./app-next/src:/app/src
    networks:
      - custom_network
  proxy:
    container_name: proxy
    build: proxy-nginx
    ports:
      - 8080:8080
    depends_on:
      - api-gemma2
      - app
    networks:
      - custom_network

networks:
  custom_network:
