services:
  api:
    container_name: api
    build: api-gemma2
    volumes:
      - ./api-gemma2/src:/app/src
    networks:
      - custom_network
  proxy:
    container_name: proxy
    build: proxy-nginx
    ports:
      - 8080:8080
    depends_on:
      - api
    networks:
      - custom_network

networks:
  custom_network:
