services:
  api-aivisspeech:
    container_name: api-aivisspeech
    build: api-aivisspeech
    volumes:
      - ./api-aivisspeech/mount/.local/share/AivisSpeech-Engine:/home/user/.local/share/AivisSpeech-Engine-Dev
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      - custom_network
  api-gemma2:
    container_name: api-gemma2
    build: api-gemma2
    volumes:
      - ./api-gemma2/src:/app/src
    networks:
      - custom_network
  app-chainlit:
    container_name: app-chainlit
    build: app-chainlit
    volumes:
      - ./app-chainlit/src:/app/src
    networks:
      - custom_network
  proxy:
    container_name: proxy
    build: proxy-nginx
    ports:
      - 8080:8080
    depends_on:
      - api-aivisspeech
      - api-gemma2
      - app-chainlit
    networks:
      - custom_network

networks:
  custom_network:
