# Stage 1: Model download
FROM debian:bullseye-slim AS model-downloader
RUN apt update && \
    apt install -y --no-install-recommends --no-install-suggests \
    git \
    git-lfs
COPY .env.public .env.secret clone_model.sh ./
RUN chmod +x clone_model.sh
RUN ./clone_model.sh /app/model && rm .env.secret
RUN rm -rf /app/model/.git

# Stage 2: Application runtime
FROM python:3.11.10-slim-bullseye
COPY --from=model-downloader /app/model /app/model
# install packages
WORKDIR /app
RUN pip install -U pip && pip install uv
COPY pyproject.toml /app/
RUN uv sync
# run fastapi
WORKDIR /app/src
COPY ./src/main.py /app/src/
CMD ["/bin/bash", "-c", "source /app/.venv/bin/activate && uvicorn main:app --host 0.0.0.0 --reload"]
