FROM debian:bullseye-slim
RUN apt update

# install rye
WORKDIR /root
RUN apt install -y curl
RUN curl -sSf https://rye.astral.sh/get | RYE_INSTALL_OPTION="--yes" bash
ENV PATH="/root/.rye/shims:$PATH"

# build python
WORKDIR /app
COPY .python-version pyproject.toml /app/
RUN rye sync

# run fastapi
WORKDIR /app/src
CMD ["/bin/bash", "-c", "source /app/.venv/bin/activate && uvicorn main:app --host 0.0.0.0 --reload"]
