# FROM ghcr.io/aivis-project/aivisspeech-engine:nvidia-latest
FROM ghcr.io/aivis-project/aivisspeech-engine:cpu-latest
ENTRYPOINT [ "/entrypoint.sh"  ]
CMD [ "gosu", "user", "/opt/python/bin/poetry", "run", "python", "./run.py", "--host", "0.0.0.0" ]
